package com.sungard.hackathon.monster.listener;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.SQLException;
import java.sql.Statement;

import org.apache.log4j.Logger;
import org.springframework.context.ApplicationEvent;
import org.springframework.context.ApplicationListener;

import com.sungard.hackathon.monster.utils.FileUtils;

public class MemoryDatabaseListener implements
		ApplicationListener<ApplicationEvent> {

	private Logger log = Logger.getLogger(this.getClass());

	@Override
	public void onApplicationEvent(ApplicationEvent event) {
		try {
			prepMemoryDatabase();
			FileUtils.cleanWorkspace();
			FileUtils.initDirs();
		} catch (Exception e) {
			log.error("Create Database Error", e);
		}
	}

	private void prepMemoryDatabase() throws SQLException {
		Connection conn = null;
		Statement st = null;

		try {
			Class.forName("org.hsqldb.jdbc.JDBCDriver");
			conn = DriverManager.getConnection("jdbc:hsqldb:mem:localDb", "SA",
					"");
			st = conn.createStatement();

			StringBuilder sb = new StringBuilder();
			sb.append("CREATE MEMORY TABLE PERSON(");
			sb.append("ID INTEGER GENERATED BY DEFAULT AS IDENTITY(START WITH 1) NOT NULL PRIMARY KEY,");
			sb.append("NAME VARCHAR(255) NOT NULL,");
			sb.append("EMAIL VARCHAR(255) NOT NULL,");
			sb.append("IMAGE1 OTHER,");
			sb.append("IMAGE2 OTHER,");
			sb.append("IMAGE3 OTHER)");
			st.executeUpdate(sb.toString());
		} catch (ClassNotFoundException e) {
			throw new SQLException("HSQLDB database driver is not found", e);
		} finally {
			if (st != null) {
				try {
					st.close();
				} catch (SQLException se) {
				}
			}
		}
	}
}
